# Site settings
title: Conference Name, Year
venue: City, Country
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write a description for your conference or meeting here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/confweb" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
future: true

permalink: "/:categories/:title.html"
banner: nice_conference_banner.jpeg

conference:
  location: City, Country
  year: 2017
  month: September
  dates:
  - 2017-09-12
  - 2017-09-13
  draft: true # set to True if the programme is draft only.
  name: CONF 2017 - Conference Name
  location: Conference Venue
  hosts:
  organizers:
  - name: Jack Jones
    url: "http://jackjones.org"
  - name: Bill Bloggs
    url: "http://billblogs.org"
